name: Windows

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        flags: ["/std:c++11", "/std:c++latest"]
        optimize: [/O2]

    env:
      CXXFLAGS: ${{ matrix.flags }} ${{ matrix.optimize }}
      CTEST_OUTPUT_ON_FAILURE: 1
      CTEST_NO_TESTS_ACTION: error
      CTEST_PARALLEL_LEVEL: 0
      CMAKE_BUILD_PARALLEL_LEVEL: 4

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: CMake configure
      run: cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -B build

    - name: CMake build
      run: cmake --build build --config Release

    - name: CMake test
      run: ctest --test-dir build -C Release
